sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
env:
  - LUAJIT=OFF
  - LUAJIT=ON
cache: apt
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-system-dev
      - libboost-iostreams-dev
      - liblua5.2-dev
      - libluajit-5.1-dev
      - libmysqlclient-dev
      - libpugixml-dev
      - build-essential
      - libgmp3-dev
before_script:
  - mkdir path_10_9/build && mkdir path_8_7/build && mkdir path_8_6/build && mkdir path_8_5/build && mkdir path_7_7/build
  - cd path_10_9/build
  - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_LUAJIT=${LUAJIT} ..
  - cd ../../path_8_7/build
  - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_LUAJIT=${LUAJIT} ..
  - cd ../../path_8_6/build
  - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_LUAJIT=${LUAJIT} ..
  - cd ../../path_8_5/build
  - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_LUAJIT=${LUAJIT} ..
  - cd ../../path_7_7/build
  - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_LUAJIT=${LUAJIT} ..
script:
  - cd ../../path_10_9/build
  - make -j2
  - cd ../../path_7_7/build
  - make -j2
